# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    

    - name: Build iOS (debug)
      run: "xcodebuild \
         -project ios/firstapp.xcodeproj \
         -scheme firstapp \
        clean \
        -sdk iphoneos \
        -configuration Debug \
        -UseModernBuildSystem=NO \
        CODE_SIGNING_ALLOWED=NO"

#     - name: Compress .xcarchive
#       run: zip -r -9 firstapp.xcarchive.zip $PWD/firstapp.xcarchive/

    - uses: actions/upload-artifact@v2
      with:
        name: ios-xarchive
        path: firstapp.xcarchive.zip
